# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Proyecto_uinkSJGK.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1013, 703)
        palette = QPalette()
        brush = QBrush(QColor(0, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(7, 5, 60, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(7, 73, 124, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush2)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 971, 231))
        self.label.setFrameShape(QFrame.Shape.Box)
        self.label.setFrameShadow(QFrame.Shadow.Sunken)
        self.label.setLineWidth(2)
        self.btnregistrar = QPushButton(self.centralwidget)
        self.btnregistrar.setObjectName(u"btnregistrar")
        self.btnregistrar.setGeometry(QRect(590, 430, 171, 81))
        palette1 = QPalette()
        brush3 = QBrush(QColor(8, 15, 60, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush3)
        brush4 = QBrush(QColor(0, 251, 255, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush4)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush4)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush3)
        self.btnregistrar.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Candara"])
        font.setPointSize(12)
        font.setBold(True)
        self.btnregistrar.setFont(font)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(40, 270, 521, 381))
        palette2 = QPalette()
        brush5 = QBrush(QColor(33, 255, 240, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush5)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush5)
        self.groupBox.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"Candara"])
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setItalic(True)
        font1.setUnderline(False)
        self.groupBox.setFont(font1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 50, 481, 41))
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 130, 481, 41))
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(20, 210, 481, 41))
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(20, 290, 481, 41))
        self.lblTemperaturaClima = QLabel(self.centralwidget)
        self.lblTemperaturaClima.setObjectName(u"lblTemperaturaClima")
        self.lblTemperaturaClima.setGeometry(QRect(810, 350, 171, 61))
        self.lblTemperaturaClima.setFrameShape(QFrame.Shape.Box)
        self.lblIconoClima = QLabel(self.centralwidget)
        self.lblIconoClima.setObjectName(u"lblIconoClima")
        self.lblIconoClima.setGeometry(QRect(590, 350, 171, 61))
        self.lblIconoClima.setFrameShape(QFrame.Shape.Box)
        self.lblHora = QLabel(self.centralwidget)
        self.lblHora.setObjectName(u"lblHora")
        self.lblHora.setGeometry(QRect(590, 280, 171, 61))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        self.lblHora.setPalette(palette3)
        self.lblHora.setFrameShape(QFrame.Shape.Box)
        self.lblFecha = QLabel(self.centralwidget)
        self.lblFecha.setObjectName(u"lblFecha")
        self.lblFecha.setGeometry(QRect(810, 280, 171, 61))
        self.lblFecha.setFrameShape(QFrame.Shape.Box)
        self.btnregistrar_2 = QPushButton(self.centralwidget)
        self.btnregistrar_2.setObjectName(u"btnregistrar_2")
        self.btnregistrar_2.setGeometry(QRect(590, 530, 171, 81))
        palette4 = QPalette()
        brush6 = QBrush(QColor(85, 0, 0, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush6)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush4)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush6)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush4)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush6)
        self.btnregistrar_2.setPalette(palette4)
        self.btnregistrar_2.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnregistrar.clicked.connect(MainWindow.registrar)
        self.btnregistrar_2.clicked.connect(MainWindow.salir)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.btnregistrar.setText(QCoreApplication.translate("MainWindow", u"REGISTRARSE", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Administrador de autos", None))
        self.lblTemperaturaClima.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lblIconoClima.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lblHora.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lblFecha.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.btnregistrar_2.setText(QCoreApplication.translate("MainWindow", u"SALIR", None))
    # retranslateUi

