# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Proyecto_uiKvJsKt.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1015, 707)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(100, 71, 13, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(84, 84, 84, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush2)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 981, 231))
        self.label.setFrameShape(QFrame.Shape.Box)
        self.label.setFrameShadow(QFrame.Shadow.Raised)
        self.label.setLineWidth(4)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 280, 521, 381))
        palette1 = QPalette()
        brush3 = QBrush(QColor(10, 10, 33, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        brush4 = QBrush(QColor(2, 0, 33, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Link, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush4)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Link, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush4)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Link, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush4)
#endif
        self.groupBox.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Segoe UI Variable"])
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 50, 481, 51))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI Variable"])
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        self.lineEdit.setFont(font1)
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 130, 481, 51))
        self.lineEdit_2.setFont(font1)
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(20, 210, 481, 51))
        self.lineEdit_3.setFont(font1)
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(20, 290, 481, 51))
        self.lineEdit_4.setFont(font1)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(560, 330, 441, 171))
        self.lblHora = QLabel(self.groupBox_2)
        self.lblHora.setObjectName(u"lblHora")
        self.lblHora.setGeometry(QRect(10, 10, 201, 61))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush3)
        brush5 = QBrush(QColor(54, 65, 124, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush5)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush3)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush5)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush5)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush5)
        self.lblHora.setPalette(palette2)
        font2 = QFont()
        font2.setFamilies([u"Segoe UI Emoji"])
        font2.setPointSize(11)
        font2.setBold(False)
        self.lblHora.setFont(font2)
        self.lblHora.setFrameShape(QFrame.Shape.WinPanel)
        self.lblHora.setFrameShadow(QFrame.Shadow.Raised)
        self.lblHora.setLineWidth(1)
        self.lblHora.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblFecha = QLabel(self.groupBox_2)
        self.lblFecha.setObjectName(u"lblFecha")
        self.lblFecha.setGeometry(QRect(230, 10, 201, 61))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush3)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush5)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush3)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush5)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush5)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush5)
        self.lblFecha.setPalette(palette3)
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Variable"])
        font3.setPointSize(11)
        font3.setBold(False)
        self.lblFecha.setFont(font3)
        self.lblFecha.setFrameShape(QFrame.Shape.WinPanel)
        self.lblFecha.setFrameShadow(QFrame.Shadow.Raised)
        self.lblFecha.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblIconoClima = QLabel(self.groupBox_2)
        self.lblIconoClima.setObjectName(u"lblIconoClima")
        self.lblIconoClima.setGeometry(QRect(10, 100, 201, 61))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush3)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush5)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush3)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush5)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush5)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush5)
        self.lblIconoClima.setPalette(palette4)
        self.lblIconoClima.setFont(font3)
        self.lblIconoClima.setFrameShape(QFrame.Shape.WinPanel)
        self.lblIconoClima.setFrameShadow(QFrame.Shadow.Raised)
        self.lblIconoClima.setLineWidth(1)
        self.lblIconoClima.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblTemperaturaClima = QLabel(self.groupBox_2)
        self.lblTemperaturaClima.setObjectName(u"lblTemperaturaClima")
        self.lblTemperaturaClima.setGeometry(QRect(230, 100, 201, 61))
        palette5 = QPalette()
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush3)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush5)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush3)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush5)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush5)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush5)
        self.lblTemperaturaClima.setPalette(palette5)
        self.lblTemperaturaClima.setFont(font3)
        self.lblTemperaturaClima.setFrameShape(QFrame.Shape.WinPanel)
        self.lblTemperaturaClima.setFrameShadow(QFrame.Shadow.Raised)
        self.lblTemperaturaClima.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(560, 510, 441, 111))
        palette6 = QPalette()
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush3)
        self.groupBox_3.setPalette(palette6)
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Variable"])
        font4.setPointSize(11)
        self.groupBox_3.setFont(font4)
        self.btnregistrar = QPushButton(self.groupBox_3)
        self.btnregistrar.setObjectName(u"btnregistrar")
        self.btnregistrar.setGeometry(QRect(10, 20, 201, 81))
        palette7 = QPalette()
        brush6 = QBrush(QColor(2, 197, 2, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush6)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush6)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush6)
        self.btnregistrar.setPalette(palette7)
        font5 = QFont()
        font5.setFamilies([u"Segoe UI Variable"])
        font5.setPointSize(14)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setKerning(True)
        self.btnregistrar.setFont(font5)
        self.btnregistrar.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoUp))
        self.btnregistrar.setIcon(icon)
        self.btnregistrar_2 = QPushButton(self.groupBox_3)
        self.btnregistrar_2.setObjectName(u"btnregistrar_2")
        self.btnregistrar_2.setGeometry(QRect(230, 20, 201, 81))
        palette8 = QPalette()
        brush7 = QBrush(QColor(163, 0, 0, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush7)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush7)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush7)
        self.btnregistrar_2.setPalette(palette8)
        font6 = QFont()
        font6.setFamilies([u"Segoe UI Variable"])
        font6.setPointSize(14)
        font6.setBold(False)
        font6.setItalic(False)
        self.btnregistrar_2.setFont(font6)
        self.btnregistrar_2.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.WindowClose))
        self.btnregistrar_2.setIcon(icon1)
        self.btnregistrar_2.setCheckable(False)
        self.btnregistrar_2.setAutoDefault(False)
        self.btnregistrar_2.setFlat(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnregistrar_2.clicked.connect(MainWindow.salir)
        self.btnregistrar.clicked.connect(MainWindow.registrar)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"VENTANA DE ADMINISTRADOR", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Administrador de autos", None))
        self.groupBox_2.setTitle("")
        self.lblHora.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lblFecha.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lblIconoClima.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.lblTemperaturaClima.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Opciones", None))
        self.btnregistrar.setText(QCoreApplication.translate("MainWindow", u"REGISTRARSE", None))
        self.btnregistrar_2.setText(QCoreApplication.translate("MainWindow", u"SALIR", None))
    # retranslateUi

